data:
    dataset: Coco
    cache_images: false
    labels:
        points: logs/export_DGX
        cache: false
    preprocessing:
        img_size: 640
        pad: 0
    suffix: jpg

    augmentation:
        photometric:
            enable: true
            enable_train: true
            enable_val: false
            params:
                random_brightness: {max_abs_change: 25}
                random_contrast: {strength_range: [0.5, 1.5]}
                additive_gaussian_noise: {stddev_range: [0, 5]}
                additive_shade:
                    transparency_range: [-0.25, 0.25]
                    kernel_size_range: [100, 150]
                motion_blur: {max_kernel_size: 3}
                add_elementwise: {value: [-8, 8], per_channel: 0.3}
                hsv: [0.017, 0.7, 0.4]
            params_light:
                channel_shuffle: 0.0
        homographic:
            enable: true
            enable_train: true
            enable_val: false
            params: # not used for mosaic
                translation: true
                rotation: true
                scaling: true
                perspective: true
                scaling_amplitude: 0.06
                perspective_amplitude_x: 0.035
                perspective_amplitude_y: 0.035
                patch_ratio: 0.9
                max_angle: 0.03  # 3.14
                allow_artifacts: true
                translation_overflow: 0.05
            mosaic:
                params:
                    translation: true
                    rotation: true # set to false for full yolo training
                    scaling: true
                    perspective: true # set to false for full yolo training
                    scaling_amplitude: 0.05
                    perspective_amplitude_x: 0.02
                    perspective_amplitude_y: 0.02
                    patch_ratio: 1.
                    allow_artifacts: true
                    translation_overflow: 0.33
                    max_angle: 0.02  # 0.02
            flipping:
                horizontal: 0.5
                vertical: 0.0
            valid_border_margin: 4
        mosaic: 1.0

    warped_pair:
        enable: true
        params:
            translation: true
            rotation: true
            scaling: true
            perspective: true
            scaling_amplitude: 0.2
            perspective_amplitude_x: 0.2
            perspective_amplitude_y: 0.2
            patch_ratio: 0.75
            max_angle: 0.785  # 1.57
            allow_artifacts: true
            translation_overflow: 0.125
        mosaic_params:
            translation: true
            rotation: true
            scaling: true
            perspective: true
            scaling_amplitude: 0.15 # 0.2
            perspective_amplitude_x: 0.25
            perspective_amplitude_y: 0.25
            patch_ratio: 0.85   # 0.85
            max_angle: 0.785 # 0.524    # 1.57
            allow_artifacts: true
            translation_overflow: 0.15
        valid_border_margin: 4
        photometric:
            enable: true
            enable_train: true
            enable_val: false
            params:
#                random_brightness: { max_abs_change: 10 }
                additive_shade:
                    transparency_range: [ -0.4,0.4 ] #[ -0.6, 0.8 ]
                    kernel_size_range: [ 50, 150 ]
                add_elementwise: { value: [ -5, 5 ], per_channel: 0.5 }
                additive_gaussian_noise: {stddev_range: [0, 5]}
                add: {value: [-8, 8], per_channel: 0.5}
                motion_blur: {max_kernel_size: 7}
                random_contrast: {strength_range: [0.3, 1.8]}
                hsv: [0.1, 0.2, 0.5]

training_params:
    workers_train: 32
    workers_val: 32
    train_batch_size: 32
    val_batch_size: 32

model:
    input_channels: 3
    lambda_loss: 0.1
    lambda_loss_obj: 10

    superpoint:
        detection_threshold: 0.085
        nms: 4
        lambda_d: 2000   # only used for dense loss
        top_k: 1000  # make variable depending on image size
        sparse_loss:
            num_samples_per_image: 3000
            num_masked_non_matches_per_match: 200
    yolo:
        conf_thres_box: 0.25
        iou_thres_box: 0.45
        classes: None   # filter by class
        agnostic_nms: False # class-agnostic NMS
        max_det: 1000
        box: 0.05
        cls: 0.5
        cls_pw: 1.0
        obj: 1.0
        obj_pw: 1.0
        iou_t: 0.2
        anchor_t: 4.0
        label_smoothing: 0.0
        fl_gamma: 0.0

optimizer:
    name: Adam     # Adam, SGD
    lr: 0.001    # 0.001 for Adam, 0.01 for SGD
#    momentum: 0.937
#    decay: 0.00001

scheduler:
    lrf: 1.0

# training
epochs: 100
validation_interval: 1
save_interval: 1
save_best: false    # saves all when false
joint_training: true
#gradient_clip: 10.0 # store if loss explodes
extended_val_sample_size: 500
filter_points: true

#pretrained: logs/YPv5/checkpoints/YPv5_20_73921_ckpt.pth.tar
#resume: True

#freeze_layers: '0-176'   # e.g. '0-3, 12, 15, 20-30'; 0-3 --> 0,1,2,3
# shared backbone: 0-44
# full backbone: 0-98
# yolo head: 99-176
# kp detector head: 177-194
# descriptor head: 195-218

#warm_start: {lamda: 0.5, sigma: 0.01}

# Classes
names: ['person', 'bicycle', 'car', 'motorcycle', 'airplane', 'bus', 'train', 'truck', 'boat', 'traffic light',
        'fire hydrant', 'stop sign', 'parking meter', 'bench', 'bird', 'cat', 'dog', 'horse', 'sheep', 'cow',
        'elephant', 'bear', 'zebra', 'giraffe', 'backpack', 'umbrella', 'handbag', 'tie', 'suitcase', 'frisbee',
        'skis', 'snowboard', 'sports ball', 'kite', 'baseball bat', 'baseball glove', 'skateboard', 'surfboard',
        'tennis racket', 'bottle', 'wine glass', 'cup', 'fork', 'knife', 'spoon', 'bowl', 'banana', 'apple',
        'sandwich', 'orange', 'broccoli', 'carrot', 'hot dog', 'pizza', 'donut', 'cake', 'chair', 'couch',
        'potted plant', 'bed', 'dining table', 'toilet', 'tv', 'laptop', 'mouse', 'remote', 'keyboard', 'cell phone',
        'microwave', 'oven', 'toaster', 'sink', 'refrigerator', 'book', 'clock', 'vase', 'scissors', 'teddy bear',
        'hair drier', 'toothbrush']