data:
    dataset: 'Kitti'
    suffix: png
    input_channels: 1
    preprocessing:
        img_size: 960
        pad: 0
    augmentation:
        photometric:
            enable: false
    homography_adaptation:
        enable: true
        num: 10 # 100
        aggregation: 'sum'
        filter_counts: 0
        homographies:
            params:
                translation: true
                rotation: true
                scaling: true
                perspective: true
                scaling_amplitude: 0.25
                perspective_amplitude_x: 0.1
                perspective_amplitude_y: 0.1
                allow_artifacts: true
                patch_ratio: 0.85 #0.85
                max_angle: 0.15
                translation_overflow: 0.15

normalize_points: false

training_params:
    workers_train: 4
    workers_val: 4
    train_batch_size: 1
    val_batch_size: 1

model:
    name: 'SuperPoint'
    train_batch_size: 1
    val_batch_size: 1
    detection_threshold: 0.015 # 0.015
    nms: 4
    top_k: 600
    input_channels: 3

pretrained: logs/SuperPointNet/checkpoints/superpoint_v1.pth

# Classes (dummy values will do)
names: ['Pedestrian', 'Car', 'Truck', 'Cyclist', 'Misc', 'Van', 'Tram']