model:
    name: 'YOLOPointv52'
    version: s
    input_channels: 3
    superpoint:
        detection_threshold: 0.12   # important
        nms: 8                      # important
        nn_thresh: 0.7              # important
        min_length: 2
        max_length: 4
    yolo:
        conf_thres_box: 0.4
        iou_thres_box: 0.45
        classes: None   # filter by class
        agnostic_nms: True # class-agnostic NMS
        max_det: 1000
        box: 0.05
        cls: 0.5
        cls_pw: 1.0
        obj: 1.0
        obj_pw: 1.0
        iou_t: 0.2
        anchor_t: 4.0
        label_smoothing: 0.0
        fl_gamma: 0.0

# Classes
names: ['Pedestrian', 'Car', 'Truck', 'Cyclist', 'Misc', 'Van', 'Tram']
